spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false

---
spring:
  config.activate.on-profile: sandbox
cds:
  remote.services:
    '[API_BUSINESS_PARTNER]':
      destination:
        type: "odata-v2"
        properties:
          url: "https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap"
        headers:
          APIKey: "" 

---
spring:
  config.activate.on-profile: sqlite
  sql:
    init:
      mode: never
  datasource:
    url: "jdbc:sqlite:sqlite.db"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 1
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false