spring:
  config.activate.on-profile: default
  sql.init.schema-locations: classpath:schema-h2.sql
  web.resources.static-locations: file:./app/
cds:
  datasource.auto-config.enabled: false

---
spring:
  config.activate.on-profile: sandbox
cds:
  remote.services:
    '[API_BUSINESS_PARTNER]':
      destination:
        type: "odata-v2"
        properties:
          url: "https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap"
        headers:
          APIKey: "" 